##                          Phase 1
### Numpy array and basics
learn about numpy with chai and code.

In [50]:
import numpy as np

### creating array from list

In [51]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array: ",arr_2d)

1D Array:  [1 2 3 4 5]
2D Array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [52]:
py_list = [1,2,3]
print("Python list Multiplication: ",py_list * 2)

np_array = np.array([1,2,3]) # element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ",time.time() - start)

Python list Multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.052330732345581055

 Numpy operation time:  0.0037479400634765625


### Creating array from Scratch



In [53]:
zeros = np.zeros((3,4))
print("zeroes Array: \n",zeros)

ones = np.ones((2,3))
print("Ones Array: \n",ones)

full = np.full((2,7),7)
print("One Array: \n",full)

random = np.random.random((2,3))
print("Random Array: \n",random)

sequence = np.arange(0,10,2)
print("Sequence Array: \n",sequence)

zeroes Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
One Array: 
 [[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]
Random Array: 
 [[0.27584423 0.11668651 0.063087  ]
 [0.74051861 0.9451763  0.27661715]]
Sequence Array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [54]:
vector = np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([ [ [1,2] ,[3,4] ],
                   [ [5,6] , [7,8] ] ])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [55]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape: ",arr.shape)
print("Dimesion: ", arr.ndim)
print("Size: ",arr.size)
print("Dtype: ",arr.dtype)


Shape:  (2, 3)
Dimesion:  2
Size:  6
Dtype:  int64


### Array Reshaping

In [56]:
arr = np.arange(12)
print("Original array: \n",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: ", flattened)

# ravel (returns view, insted of copy)
raveled = reshaped.ravel()
print("\n Raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("Transposed Array: \n",transpose)

Original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
