## Phase 2
### Numpy array Operations 

In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("with step: ",arr[1:6:2])
print("Negative Indexing: ",arr[-3])

Basic Slicing:  [3 4 5 6 7]
with step:  [2 4 6]
Negative Indexing:  8


In [10]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element: \n", arr_2d[1,2])
print("Entire Row: \n",arr_2d[1])
print("Entire Column: \n",arr_2d[:,1])

Specific element: 
 6
Entire Row: 
 [4 5 6]
Entire Column: 
 [2 5 8]


## Sorting

In [3]:
unsorted = np.array([3,1,4,2,5,6,8,7,9])
print("Sorted Array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],
                            [2,4],[4,3]])
print("Sorted 2-D array by coloumn: \n",np.sort(arr_2d_unsorted, axis=0))

Sorted Array:  [1 2 3 4 5 6 7 8 9]
Sorted 2-D array by coloumn: 
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]


## Filter

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ",even_number)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask 

In [12]:
mask = numbers > 5
print("Numbers greater than 5: ",numbers[mask])


Numbers greater than 5:  [ 6  7  8  9 10]


## Fancey indexing vs np.where()

In [14]:
indices = [0,2,4]
print(numbers[indices])

when_result = np.where( numbers > 5)
print("NP where: ",numbers[when_result])



[1 3 5]
NP where:  [ 6  7  8  9 10]


In [18]:
# condition_array = np.where(condition, statement 1 if true condition,
# statement 2 if condition false)
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing data

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
# combined_array = arr1 + arr2   --> Wrong method it adds not merge.
# print(combined_array)
combined_array = np.concatenate((arr1,arr2))
print(combined_array)

[1 2 3 4 5 6]


### Array compatibility

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility shapes: ",a.shape == b.shape)


Compatibility shapes:  True


In [30]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("Row added:\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("Coloumn added: \n",with_new_col)

[[1 2]
 [3 4]]
Row added:
 [[1 2]
 [3 4]
 [5 6]]
Coloumn added: 
 [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion: ",deleted)

Array after deletion:  [1 2 4 5]
