## Phase 1 Revision


In [2]:
import numpy as np 

In [5]:
arr_1d = np.array([1,2,3])
print("1D array: ",arr_1d)

arr_2d = np.array([[1,2],[3,4]])
print("2D array: \n",arr_2d)

1D array:  [1 2 3]
2D array: 
 [[1 2]
 [3 4]]


In [8]:
my_list = [1,2,3]
print("Python list: ",my_list)

arr = np.array([[1,2,3],[4,5,6]])
print("Numpy array: \n",arr)

Python list:  [1, 2, 3]
Numpy array: 
 [[1 2 3]
 [4 5 6]]


In [12]:
zeros = np.zeros((3,4))
print("Zero array: \n",zeros)

ones = np.ones((4,5))
print("Ones array: \n",ones)

full = np.full((2,3),10)
print("Full array: \n",full)

random = np.random.random((3,4))
print("Random array: \n",random)

sequence = np.arange(1,10,3)
print("Sequence array: ",sequence)

Zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full array: 
 [[10 10 10]
 [10 10 10]]
Random array: 
 [[0.91106454 0.27883599 0.38653947 0.44663673]
 [0.8274052  0.24977675 0.217466   0.93744901]
 [0.96525029 0.45829989 0.5796268  0.80381021]]
Sequence array:  [1 4 7]


In [15]:
vector = np.array([1,2,3])
print("Vector array: ",vector)

matrix = np.array([[1,2],[3,4]])
print("Matrix array: \n",matrix)

tensor = np.array([[[1,2],[4,3]],
                   [[5,6],[8,7]]])
print("Tensor array: \n", tensor)


Vector array:  [1 2 3]
Matrix array: 
 [[1 2]
 [3 4]]
Tensor array: 
 [[[1 2]
  [4 3]]

 [[5 6]
  [8 7]]]


In [17]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array: \n",arr_2D)
print("Shape: ",arr_2D.shape)
print("Size: ",arr_2D.size)
print("Dimension: ",arr_2D.ndim)
print("Data type: ",arr_2D.dtype)

2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size:  9
Dimension:  2
Data type:  int64


In [3]:
arr_og = np.arange(12)
print("Original array: ",arr_og)

reshaped = arr_og.reshape((3,4))
print("Reshaped array: \n",reshaped)

flattened = reshaped.flatten()
print("Flatened array: \n",flattened)

raveled = reshaped.ravel()
print("Raveled array: \n",raveled)

transpose = reshaped.T 
print("Transpose array: \n",transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Phase 2 Revision

In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ",arr[1:4])
print("With Step: ",arr[1:10:2])
print("Negative Indexing: ",arr[-5:-1])

Basic Slicing:  [2 3 4]
With Step:  [ 2  4  6  8 10]
Negative Indexing:  [6 7 8 9]


In [27]:
arr2d =np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]]) 
print("Specific Element: ", arr2d[2,2])
print("Specific Coloumn: ",arr2d[:,1])
print("Specific Row: ",arr2d[1])

Specific Element:  9
Specific Coloumn:  [2 5 8]
Specific Row:  [4 5 6]


In [34]:
a1d = np.array([1,5,3,6,2])
print("1D Sort: ",np.sort(a1d))

a2d = np.array([[2,1],
               [3,2],
               [1,3]])
print("2D Sort: ",np.sort(a2d,axis=0))

1D Sort:  [1 2 3 5 6]
2D Sort:  [[1 1]
 [2 2]
 [3 3]]
